# Generated by Django 5.2.12 on 2026-03-17 10:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('badge_emoji', models.CharField(max_length=10)),
                ('condition_type', models.CharField(max_length=50)),
                ('condition_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('context_detail', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('campus', 'Campus Catastrophes'), ('food', 'Food Court Fiascos'), ('social', 'Social Misfires'), ('digital', 'Digital Disasters'), ('public', 'Public Nightmares')], max_length=50)),
                ('location_emoji', models.CharField(default='LOC', max_length=10)),
                ('location_name', models.CharField(max_length=100)),
                ('witness_count', models.IntegerField(default=0)),
                ('is_start', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('inner_monologue', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('confidence', models.IntegerField(default=50)),
                ('awkwardness', models.IntegerField(default=0)),
                ('scenario_pool', models.JSONField(default=list)),
                ('current_index', models.IntegerField(default=0)),
                ('choices_made', models.JSONField(default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('final_score', models.IntegerField(blank=True, null=True)),
                ('ending_title', models.CharField(blank=True, max_length=100)),
                ('ending_description', models.CharField(blank=True, max_length=240)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('timer_mode', models.BooleanField(default=False)),
                ('random_mode', models.BooleanField(default=True)),
                ('current_scenario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('choice_type', models.CharField(choices=[('ignore', 'Pretend Nothing Happened'), ('laugh', 'Laugh It Off'), ('escape', 'Escape The Situation'), ('escalate', 'Make It Worse')], max_length=20)),
                ('emoji_hint', models.CharField(default='>', max_length=10)),
                ('confidence_effect', models.IntegerField()),
                ('awkwardness_effect', models.IntegerField()),
                ('outcome_text', models.TextField()),
                ('witness_reaction', models.CharField(blank=True, max_length=200)),
                ('triggers_callback', models.BooleanField(default=False)),
                ('callback_text', models.CharField(blank=True, max_length=300)),
                ('next_scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_choices', to='game.scenario')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='game.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='SessionAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.achievement')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamesession')),
            ],
            options={
                'unique_together': {('session', 'achievement')},
            },
        ),
    ]
